name: example-servant-elm

dependencies:
  - base
  - warp
  - aeson
  - wai-make-assets
  - servant-elm
  - servant
  - wai
  - servant-server
  - transformers
  - containers

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
